### ISSUE TITLE
404 css和js 路径都不对

### ISSUE THREAD

**Issue by xiafei114** [kokdemo/jandan-pic-maker#3]
![image](https://user-images.githubusercontent.com/27845805/72773480-37ce5a80-3c42-11ea-912c-72cf5102ca93.png)

![image](https://user-images.githubusercontent.com/27845805/72773439-179e9b80-3c42-11ea-93b5-c6e006493d7c.png)

**Comment by kokdemo** [comment]
修复了，parcel打包器的锅
